services:
  postgres:
    # image: pgvector/pgvector:pg16
    image: pgvector/pgvector:pg16
    container_name: from_rag_to_graphrag-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - from_rag_to_graphrag_net
    ports:
      - '5435:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d dev_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  neo4j:
    image: neo4j:5-community
    container_name: from_rag_to_graphrag-neo4j
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/dev_password
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - from_rag_to_graphrag_net
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  from_rag_to_graphrag_net:
    driver: bridge

volumes:
  postgres_data:
  neo4j_data:
