export const MOVIES = [
  // Christopher Nolan
  {
    title: 'Inception',
    director: 'Christopher Nolan',
    genre: 'Sci-Fi',
    year: 2010,
    actors: [
      'Leonardo DiCaprio',
      'Joseph Gordon-Levitt',
      'Elliot Page',
      'Tom Hardy',
      'Cillian Murphy',
    ],
    plot: 'A thief steals secrets through dream-sharing.',
  },
  {
    title: 'The Dark Knight',
    director: 'Christopher Nolan',
    genre: 'Action',
    year: 2008,
    actors: [
      'Christian Bale',
      'Heath Ledger',
      'Aaron Eckhart',
      'Cillian Murphy',
    ],
    plot: 'Batman faces the Joker.',
  },
  {
    title: 'The Dark Knight Rises',
    director: 'Christopher Nolan',
    genre: 'Action',
    year: 2012,
    actors: ['Christian Bale', 'Tom Hardy', 'Anne Hathaway', 'Cillian Murphy'],
    plot: 'Batman returns to face Bane.',
  },
  {
    title: 'Batman Begins',
    director: 'Christopher Nolan',
    genre: 'Action',
    year: 2005,
    actors: [
      'Christian Bale',
      'Michael Caine',
      'Liam Neeson',
      'Cillian Murphy',
    ],
    plot: 'Bruce Wayne becomes Batman.',
  },
  {
    title: 'Interstellar',
    director: 'Christopher Nolan',
    genre: 'Sci-Fi',
    year: 2014,
    actors: [
      'Matthew McConaughey',
      'Anne Hathaway',
      'Jessica Chastain',
      'Matt Damon',
    ],
    plot: 'Explorers travel through a wormhole.',
  },
  {
    title: 'The Prestige',
    director: 'Christopher Nolan',
    genre: 'Drama',
    year: 2006,
    actors: [
      'Christian Bale',
      'Hugh Jackman',
      'Scarlett Johansson',
      'Michael Caine',
    ],
    plot: 'Magicians compete for the ultimate illusion.',
  },
  {
    title: 'Dunkirk',
    director: 'Christopher Nolan',
    genre: 'War',
    year: 2017,
    actors: ['Fionn Whitehead', 'Tom Hardy', 'Cillian Murphy', 'Harry Styles'],
    plot: 'WWII evacuation from Dunkirk.',
  },
  {
    title: 'Oppenheimer',
    director: 'Christopher Nolan',
    genre: 'Biography',
    year: 2023,
    actors: [
      'Cillian Murphy',
      'Robert Downey Jr.',
      'Emily Blunt',
      'Matt Damon',
    ],
    plot: 'The story of the atomic bomb.',
  },
  {
    title: 'Tenet',
    director: 'Christopher Nolan',
    genre: 'Sci-Fi',
    year: 2020,
    actors: [
      'John David Washington',
      'Robert Pattinson',
      'Elizabeth Debicki',
      'Michael Caine',
    ],
    plot: 'Time manipulation in a global spy mission.',
  },
  {
    title: 'Memento',
    director: 'Christopher Nolan',
    genre: 'Mystery',
    year: 2000,
    actors: ['Guy Pearce', 'Carrie-Anne Moss', 'Joe Pantoliano'],
    plot: 'A man with short-term memory loss seeks revenge.',
  },

  // Martin Scorsese
  {
    title: 'The Wolf of Wall Street',
    director: 'Martin Scorsese',
    genre: 'Drama',
    year: 2013,
    actors: ['Leonardo DiCaprio', 'Jonah Hill', 'Margot Robbie'],
    plot: 'The rise and fall of Jordan Belfort.',
  },
  {
    title: 'Shutter Island',
    director: 'Martin Scorsese',
    genre: 'Mystery',
    year: 2010,
    actors: ['Leonardo DiCaprio', 'Mark Ruffalo', 'Ben Kingsley'],
    plot: 'U.S. Marshal investigates a disappearance at a mental hospital.',
  },
  {
    title: 'The Departed',
    director: 'Martin Scorsese',
    genre: 'Crime',
    year: 2006,
    actors: [
      'Leonardo DiCaprio',
      'Matt Damon',
      'Jack Nicholson',
      'Mark Wahlberg',
    ],
    plot: 'Undercover cop and mole in the mob.',
  },
  {
    title: 'Goodfellas',
    director: 'Martin Scorsese',
    genre: 'Crime',
    year: 1990,
    actors: ['Robert De Niro', 'Ray Liotta', 'Joe Pesci'],
    plot: 'The life of Henry Hill in the mob.',
  },
  {
    title: 'Casino',
    director: 'Martin Scorsese',
    genre: 'Crime',
    year: 1995,
    actors: ['Robert De Niro', 'Sharon Stone', 'Joe Pesci'],
    plot: 'Mob-controlled casino in Las Vegas.',
  },
  {
    title: 'The Irishman',
    director: 'Martin Scorsese',
    genre: 'Crime',
    year: 2019,
    actors: ['Robert De Niro', 'Al Pacino', 'Joe Pesci'],
    plot: 'A hitman recalls his involvement with Jimmy Hoffa.',
  },
  {
    title: 'Killers of the Flower Moon',
    director: 'Martin Scorsese',
    genre: 'Crime',
    year: 2023,
    actors: ['Leonardo DiCaprio', 'Robert De Niro', 'Lily Gladstone'],
    plot: 'Murders in the Osage Nation.',
  },
  {
    title: 'Gangs of New York',
    director: 'Martin Scorsese',
    genre: 'Drama',
    year: 2002,
    actors: ['Leonardo DiCaprio', 'Daniel Day-Lewis', 'Cameron Diaz'],
    plot: 'Vengeance in 1860s New York.',
  },
  {
    title: 'The Aviator',
    director: 'Martin Scorsese',
    genre: 'Biography',
    year: 2004,
    actors: ['Leonardo DiCaprio', 'Cate Blanchett', 'Kate Beckinsale'],
    plot: 'The life of Howard Hughes.',
  },

  // Quentin Tarantino
  {
    title: 'Pulp Fiction',
    director: 'Quentin Tarantino',
    genre: 'Crime',
    year: 1994,
    actors: [
      'John Travolta',
      'Uma Thurman',
      'Samuel L. Jackson',
      'Bruce Willis',
    ],
    plot: 'Intertwined crime stories in LA.',
  },
  {
    title: 'Django Unchained',
    director: 'Quentin Tarantino',
    genre: 'Western',
    year: 2012,
    actors: [
      'Jamie Foxx',
      'Christoph Waltz',
      'Leonardo DiCaprio',
      'Samuel L. Jackson',
    ],
    plot: 'A freed slave rescues his wife.',
  },
  {
    title: 'Inglourious Basterds',
    director: 'Quentin Tarantino',
    genre: 'War',
    year: 2009,
    actors: [
      'Brad Pitt',
      'Christoph Waltz',
      'Michael Fassbender',
      'Diane Kruger',
    ],
    plot: 'Jewish soldiers hunt Nazis in WWII.',
  },
  {
    title: 'Once Upon a Time in Hollywood',
    director: 'Quentin Tarantino',
    genre: 'Comedy',
    year: 2019,
    actors: ['Leonardo DiCaprio', 'Brad Pitt', 'Margot Robbie'],
    plot: 'An actor and his stunt double in 1969 LA.',
  },
  {
    title: 'Kill Bill: Vol. 1',
    director: 'Quentin Tarantino',
    genre: 'Action',
    year: 2003,
    actors: ['Uma Thurman', 'Lucy Liu', 'Vivica A. Fox'],
    plot: 'The Bride seeks revenge.',
  },
  {
    title: 'Kill Bill: Vol. 2',
    director: 'Quentin Tarantino',
    genre: 'Action',
    year: 2004,
    actors: ['Uma Thurman', 'David Carradine', 'Michael Madsen'],
    plot: 'The Bride continues her revenge.',
  },
  {
    title: 'Reservoir Dogs',
    director: 'Quentin Tarantino',
    genre: 'Crime',
    year: 1992,
    actors: ['Harvey Keitel', 'Tim Roth', 'Michael Madsen'],
    plot: 'A heist goes wrong.',
  },
  {
    title: 'The Hateful Eight',
    director: 'Quentin Tarantino',
    genre: 'Western',
    year: 2015,
    actors: ['Samuel L. Jackson', 'Kurt Russell', 'Jennifer Jason Leigh'],
    plot: 'Bounty hunters seek shelter during a blizzard.',
  },
  {
    title: 'Jackie Brown',
    director: 'Quentin Tarantino',
    genre: 'Crime',
    year: 1997,
    actors: ['Pam Grier', 'Samuel L. Jackson', 'Robert Forster'],
    plot: 'A flight attendant smuggles money.',
  },

  // Denis Villeneuve
  {
    title: 'Arrival',
    director: 'Denis Villeneuve',
    genre: 'Sci-Fi',
    year: 2016,
    actors: ['Amy Adams', 'Jeremy Renner', 'Forest Whitaker'],
    plot: 'Communicating with aliens.',
  },
  {
    title: 'Blade Runner 2049',
    director: 'Denis Villeneuve',
    genre: 'Sci-Fi',
    year: 2017,
    actors: ['Ryan Gosling', 'Harrison Ford', 'Ana de Armas'],
    plot: 'A new blade runner seeks Deckard.',
  },
  {
    title: 'Dune',
    director: 'Denis Villeneuve',
    genre: 'Sci-Fi',
    year: 2021,
    actors: [
      'Timothée Chalamet',
      'Rebecca Ferguson',
      'Oscar Isaac',
      'Zendaya',
      'Josh Brolin',
    ],
    plot: 'The battle for the desert planet Arrakis.',
  },
  {
    title: 'Dune: Part Two',
    director: 'Denis Villeneuve',
    genre: 'Sci-Fi',
    year: 2024,
    actors: [
      'Timothée Chalamet',
      'Zendaya',
      'Austin Butler',
      'Florence Pugh',
      'Josh Brolin',
    ],
    plot: 'Paul Atreides unites with the Fremen.',
  },
  {
    title: 'Sicario',
    director: 'Denis Villeneuve',
    genre: 'Action',
    year: 2015,
    actors: ['Emily Blunt', 'Benicio del Toro', 'Josh Brolin'],
    plot: 'Drug war on the US-Mexico border.',
  },
  {
    title: 'Prisoners',
    director: 'Denis Villeneuve',
    genre: 'Mystery',
    year: 2013,
    actors: ['Hugh Jackman', 'Jake Gyllenhaal', 'Viola Davis'],
    plot: 'A father takes the law into his own hands.',
  },
  {
    title: 'Enemy',
    director: 'Denis Villeneuve',
    genre: 'Mystery',
    year: 2013,
    actors: ['Jake Gyllenhaal', 'Mélanie Laurent', 'Sarah Gadon'],
    plot: 'A man finds his doppelgänger.',
  },

  // David Fincher
  {
    title: 'Fight Club',
    director: 'David Fincher',
    genre: 'Drama',
    year: 1999,
    actors: ['Brad Pitt', 'Edward Norton', 'Helena Bonham Carter'],
    plot: 'An insomniac forms an underground fight club.',
  },
  {
    title: 'Se7en',
    director: 'David Fincher',
    genre: 'Crime',
    year: 1995,
    actors: ['Brad Pitt', 'Morgan Freeman', 'Gwyneth Paltrow'],
    plot: 'Detectives hunt a serial killer using the seven deadly sins.',
  },
  {
    title: 'The Social Network',
    director: 'David Fincher',
    genre: 'Biography',
    year: 2010,
    actors: ['Jesse Eisenberg', 'Andrew Garfield', 'Justin Timberlake'],
    plot: 'The founding of Facebook.',
  },
  {
    title: 'Gone Girl',
    director: 'David Fincher',
    genre: 'Mystery',
    year: 2014,
    actors: ['Ben Affleck', 'Rosamund Pike', 'Neil Patrick Harris'],
    plot: 'A man becomes the suspect in his wifes disappearance.',
  },
  {
    title: 'Zodiac',
    director: 'David Fincher',
    genre: 'Crime',
    year: 2007,
    actors: ['Jake Gyllenhaal', 'Mark Ruffalo', 'Robert Downey Jr.'],
    plot: 'The hunt for the Zodiac killer.',
  },
  {
    title: 'The Curious Case of Benjamin Button',
    director: 'David Fincher',
    genre: 'Drama',
    year: 2008,
    actors: ['Brad Pitt', 'Cate Blanchett', 'Tilda Swinton'],
    plot: 'A man ages backwards.',
  },

  // Greta Gerwig
  {
    title: 'Lady Bird',
    director: 'Greta Gerwig',
    genre: 'Comedy',
    year: 2017,
    actors: ['Saoirse Ronan', 'Laurie Metcalf', 'Timothée Chalamet'],
    plot: 'A high school senior navigates her relationship with her mother.',
  },
  {
    title: 'Little Women',
    director: 'Greta Gerwig',
    genre: 'Drama',
    year: 2019,
    actors: [
      'Saoirse Ronan',
      'Emma Watson',
      'Florence Pugh',
      'Timothée Chalamet',
    ],
    plot: 'The lives of four sisters in the aftermath of the Civil War.',
  },
  {
    title: 'Barbie',
    director: 'Greta Gerwig',
    genre: 'Comedy',
    year: 2023,
    actors: ['Margot Robbie', 'Ryan Gosling', 'America Ferrera'],
    plot: 'Barbie travels to the real world.',
  },

  // Wes Anderson
  {
    title: 'The Grand Budapest Hotel',
    director: 'Wes Anderson',
    genre: 'Comedy',
    year: 2014,
    actors: [
      'Ralph Fiennes',
      'Tony Revolori',
      'Willem Dafoe',
      'Edward Norton',
      'Saoirse Ronan',
    ],
    plot: 'A legendary concierge and his lobby boy.',
  },
  {
    title: 'Moonrise Kingdom',
    director: 'Wes Anderson',
    genre: 'Comedy',
    year: 2012,
    actors: [
      'Bruce Willis',
      'Edward Norton',
      'Bill Murray',
      'Frances McDormand',
    ],
    plot: 'Two young lovers run away from their island town.',
  },
  {
    title: 'The Royal Tenenbaums',
    director: 'Wes Anderson',
    genre: 'Comedy',
    year: 2001,
    actors: ['Gene Hackman', 'Gwyneth Paltrow', 'Ben Stiller', 'Bill Murray'],
    plot: 'A dysfunctional family of geniuses reunites.',
  },
  {
    title: 'The French Dispatch',
    director: 'Wes Anderson',
    genre: 'Comedy',
    year: 2021,
    actors: [
      'Benicio del Toro',
      'Adrien Brody',
      'Tilda Swinton',
      'Timothée Chalamet',
      'Bill Murray',
      'Frances McDormand',
    ],
    plot: 'Stories from the final issue of an American magazine.',
  },
  {
    title: 'Asteroid City',
    director: 'Wes Anderson',
    genre: 'Comedy',
    year: 2023,
    actors: [
      'Jason Schwartzman',
      'Scarlett Johansson',
      'Tom Hanks',
      'Bryan Cranston',
      'Edward Norton',
      'Margot Robbie',
    ],
    plot: 'A stargazing convention is disrupted by world-changing events.',
  },

  // Marvel / Action Overlaps
  {
    title: 'Avengers: Endgame',
    director: 'Anthony Russo',
    genre: 'Action',
    year: 2019,
    actors: [
      'Robert Downey Jr.',
      'Chris Evans',
      'Mark Ruffalo',
      'Chris Hemsworth',
      'Scarlett Johansson',
      'Josh Brolin',
    ],
    plot: 'The final stand against Thanos.',
  },
  {
    title: 'Iron Man',
    director: 'Jon Favreau',
    genre: 'Action',
    year: 2008,
    actors: ['Robert Downey Jr.', 'Gwyneth Paltrow', 'Jeff Bridges'],
    plot: 'Tony Stark builds a suit of armor.',
  },
  {
    title: 'Captain America: Civil War',
    director: 'Anthony Russo',
    genre: 'Action',
    year: 2016,
    actors: [
      'Chris Evans',
      'Robert Downey Jr.',
      'Scarlett Johansson',
      'Sebastian Stan',
    ],
    plot: 'Fracture in the Avengers.',
  },
  {
    title: 'The Avengers',
    director: 'Joss Whedon',
    genre: 'Action',
    year: 2012,
    actors: [
      'Robert Downey Jr.',
      'Chris Evans',
      'Mark Ruffalo',
      'Chris Hemsworth',
      'Scarlett Johansson',
      'Samuel L. Jackson',
    ],
    plot: 'Earths mightiest heroes unite.',
  },
  {
    title: 'Black Widow',
    director: 'Cate Shortland',
    genre: 'Action',
    year: 2021,
    actors: ['Scarlett Johansson', 'Florence Pugh', 'David Harbour'],
    plot: 'Natasha Romanoff confronts her past.',
  },

  // Variety / Interconnected
  {
    title: 'The Martian',
    director: 'Ridley Scott',
    genre: 'Sci-Fi',
    year: 2015,
    actors: ['Matt Damon', 'Jessica Chastain', 'Kristen Wiig'],
    plot: 'Astronaut stranded on Mars.',
  },
  {
    title: 'Good Will Hunting',
    director: 'Gus Van Sant',
    genre: 'Drama',
    year: 1997,
    actors: ['Matt Damon', 'Ben Affleck', 'Robin Williams'],
    plot: 'A janitor at MIT has a gift for mathematics.',
  },
  {
    title: "Ocean's Eleven",
    director: 'Steven Soderbergh',
    genre: 'Crime',
    year: 2001,
    actors: ['George Clooney', 'Brad Pitt', 'Matt Damon', 'Julia Roberts'],
    plot: 'A team of eleven thieves rob three Las Vegas casinos.',
  },
  {
    title: "Ocean's Twelve",
    director: 'Steven Soderbergh',
    genre: 'Crime',
    year: 2004,
    actors: [
      'George Clooney',
      'Brad Pitt',
      'Matt Damon',
      'Catherine Zeta-Jones',
    ],
    plot: 'The team returns for a heist in Europe.',
  },
  {
    title: "Ocean's Thirteen",
    director: 'Steven Soderbergh',
    genre: 'Crime',
    year: 2007,
    actors: ['George Clooney', 'Brad Pitt', 'Matt Damon', 'Al Pacino'],
    plot: 'The team seeks revenge for a friend.',
  },
  {
    title: 'Saving Private Ryan',
    director: 'Steven Spielberg',
    genre: 'War',
    year: 1998,
    actors: ['Tom Hanks', 'Matt Damon', 'Tom Sizemore'],
    plot: 'A group of soldiers go behind enemy lines to rescue a paratrooper.',
  },
  {
    title: 'Forrest Gump',
    director: 'Robert Zemeckis',
    genre: 'Drama',
    year: 1994,
    actors: ['Tom Hanks', 'Robin Wright', 'Gary Sinise'],
    plot: 'The life of a man with low IQ who witness history.',
  },
  {
    title: 'Cast Away',
    director: 'Robert Zemeckis',
    genre: 'Adventure',
    year: 2000,
    actors: ['Tom Hanks', 'Helen Hunt'],
    plot: 'A FedEx executive is stranded on a deserted island.',
  },
  {
    title: 'The Terminal',
    director: 'Steven Spielberg',
    genre: 'Comedy',
    year: 2004,
    actors: ['Tom Hanks', 'Catherine Zeta-Jones', 'Stanley Tucci'],
    plot: 'A man lives in an airport terminal.',
  },
  {
    title: 'Catch Me If You Can',
    director: 'Steven Spielberg',
    genre: 'Biography',
    year: 2002,
    actors: ['Leonardo DiCaprio', 'Tom Hanks', 'Christopher Walken'],
    plot: 'A young con artist is pursued by an FBI agent.',
  },
  {
    title: 'Titanic',
    director: 'James Cameron',
    genre: 'Romance',
    year: 1997,
    actors: ['Leonardo DiCaprio', 'Kate Winslet', 'Billy Zane'],
    plot: 'Love story on the ill-fated ship.',
  },
  {
    title: 'Revolutionary Road',
    director: 'Sam Mendes',
    genre: 'Drama',
    year: 2008,
    actors: ['Leonardo DiCaprio', 'Kate Winslet', 'Kathy Bates'],
    plot: 'A couple struggles with a crumbling marriage.',
  },
  {
    title: 'The Great Gatsby',
    director: 'Baz Luhrmann',
    genre: 'Drama',
    year: 2013,
    actors: ['Leonardo DiCaprio', 'Tobey Maguire', 'Carey Mulligan'],
    plot: 'A writer is drawn into the world of Jay Gatsby.',
  },
  {
    title: 'Spiderman: No Way Home',
    director: 'Jon Watts',
    genre: 'Action',
    year: 2021,
    actors: [
      'Tom Holland',
      'Zendaya',
      'Benedict Cumberbatch',
      'Tobey Maguire',
      'Andrew Garfield',
    ],
    plot: 'Peter Parker seeks help from Doctor Strange.',
  },
  {
    title: 'The Revenant',
    director: 'Alejandro González Iñárritu',
    genre: 'Adventure',
    year: 2015,
    actors: ['Leonardo DiCaprio', 'Tom Hardy', 'Will Poulter'],
    plot: 'Survival after a bear mauling.',
  },
  {
    title: 'Birdman',
    director: 'Alejandro González Iñárritu',
    genre: 'Comedy',
    year: 2014,
    actors: ['Michael Keaton', 'Edward Norton', 'Emma Stone'],
    plot: 'A faded superhero actor tries to stage a play.',
  },
  {
    title: 'The Nice Guys',
    director: 'Shane Black',
    genre: 'Action',
    year: 2016,
    actors: ['Ryan Gosling', 'Russell Crowe', 'Angourie Rice'],
    plot: 'Private eyes in 1970s LA.',
  },
  {
    title: 'Drive',
    director: 'Nicolas Winding Refn',
    genre: 'Action',
    year: 2011,
    actors: ['Ryan Gosling', 'Carey Mulligan', 'Bryan Cranston'],
    plot: 'A stunt driver moonlights as a getaway driver.',
  },
  {
    title: 'Blue Valentine',
    director: 'Derek Cianfrance',
    genre: 'Romance',
    year: 2010,
    actors: ['Ryan Gosling', 'Michelle Williams'],
    plot: 'The rise and fall of a marriage.',
  },
  {
    title: 'The Gray Man',
    director: 'Anthony Russo',
    genre: 'Action',
    year: 2022,
    actors: ['Ryan Gosling', 'Chris Evans', 'Ana de Armas'],
    plot: 'CIA assassin on the run.',
  },
  {
    title: 'Knives Out',
    director: 'Rian Johnson',
    genre: 'Mystery',
    year: 2019,
    actors: ['Daniel Craig', 'Chris Evans', 'Ana de Armas', 'Jamie Lee Curtis'],
    plot: 'Detective investigates the death of a patriarch.',
  },
  {
    title: 'Glass Onion',
    director: 'Rian Johnson',
    genre: 'Mystery',
    year: 2022,
    actors: ['Daniel Craig', 'Edward Norton', 'Janelle Monáe', 'Kate Hudson'],
    plot: 'Benoit Blanc solves a mystery on a private island.',
  },
  {
    title: 'The Hateful Eight',
    director: 'Quentin Tarantino',
    genre: 'Western',
    year: 2015,
    actors: ['Samuel L. Jackson', 'Kurt Russell', 'Jennifer Jason Leigh'],
    plot: 'Bounty hunters in a blizzard.',
  },
  {
    title: 'Django Unchained',
    director: 'Quentin Tarantino',
    genre: 'Western',
    year: 2012,
    actors: [
      'Jamie Foxx',
      'Christoph Waltz',
      'Leonardo DiCaprio',
      'Samuel L. Jackson',
    ],
    plot: 'Freed slave rescues wife.',
  },
  {
    title: 'The Big Short',
    director: 'Adam McKay',
    genre: 'Biography',
    year: 2015,
    actors: ['Christian Bale', 'Steve Carell', 'Ryan Gosling', 'Brad Pitt'],
    plot: 'Investors bet against the housing market.',
  },
  {
    title: 'Vice',
    director: 'Adam McKay',
    genre: 'Biography',
    year: 2018,
    actors: ['Christian Bale', 'Amy Adams', 'Steve Carell'],
    plot: 'The story of Dick Cheney.',
  },
  {
    title: 'American Hustle',
    director: 'David O. Russell',
    genre: 'Crime',
    year: 2013,
    actors: [
      'Christian Bale',
      'Bradley Cooper',
      'Amy Adams',
      'Jennifer Lawrence',
      'Jeremy Renner',
    ],
    plot: 'Con artists forced to work with FBI.',
  },
  {
    title: 'Silver Linings Playbook',
    director: 'David O. Russell',
    genre: 'Romance',
    year: 2012,
    actors: ['Bradley Cooper', 'Jennifer Lawrence', 'Robert De Niro'],
    plot: 'A man with bipolar disorder tries to win back his wife.',
  },
  {
    title: 'The Hunger Games',
    director: 'Gary Ross',
    genre: 'Action',
    year: 2012,
    actors: ['Jennifer Lawrence', 'Josh Hutcherson', 'Liam Hemsworth'],
    plot: 'Teens fight to the death in a televised event.',
  },
  {
    title: 'X-Men: First Class',
    director: 'Matthew Vaughn',
    genre: 'Action',
    year: 2011,
    actors: [
      'James McAvoy',
      'Michael Fassbender',
      'Jennifer Lawrence',
      'Nicholas Hoult',
    ],
    plot: 'Origins of the X-Men.',
  },
  {
    title: 'Mad Max: Fury Road',
    director: 'George Miller',
    genre: 'Action',
    year: 2015,
    actors: ['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult'],
    plot: 'Escape from a warlord in a desert wasteland.',
  },
  {
    title: 'The Menu',
    director: 'Mark Mylod',
    genre: 'Horror',
    year: 2022,
    actors: ['Ralph Fiennes', 'Anya Taylor-Joy', 'Nicholas Hoult'],
    plot: 'A dining experience at an exclusive restaurant.',
  },
  {
    title: 'Last Night in Soho',
    director: 'Edgar Wright',
    genre: 'Horror',
    year: 2021,
    actors: ['Thomasin McKenzie', 'Anya Taylor-Joy', 'Matt Smith'],
    plot: 'A fashion student travels back to 1960s London.',
  },
  {
    title: "The Queen's Gambit (TV Mini-Series)",
    director: 'Scott Frank',
    genre: 'Drama',
    year: 2020,
    actors: ['Anya Taylor-Joy', 'Thomas Brodie-Sangster'],
    plot: 'Chess prodigy seeks to become the world master.',
  },
  {
    title: 'The Witch',
    director: 'Robert Eggers',
    genre: 'Horror',
    year: 2015,
    actors: ['Anya Taylor-Joy', 'Ralph Ineson', 'Kate Dickie'],
    plot: 'A family in 1630s New England is plagued by witchcraft.',
  },
  {
    title: 'The Northman',
    director: 'Robert Eggers',
    genre: 'Action',
    year: 2022,
    actors: [
      'Alexander Skarsgård',
      'Nicole Kidman',
      'Claes Bang',
      'Anya Taylor-Joy',
      'Ethan Hawke',
      'Willem Dafoe',
    ],
    plot: 'A Viking prince seeks justice for his murdered father.',
  },
  {
    title: 'The Lighthouse',
    director: 'Robert Eggers',
    genre: 'Horror',
    year: 2019,
    actors: ['Willem Dafoe', 'Robert Pattinson'],
    plot: 'Two lighthouse keepers descend into madness.',
  },
  {
    title: 'Poor Things',
    director: 'Yorgos Lanthimos',
    genre: 'Comedy',
    year: 2023,
    actors: ['Emma Stone', 'Mark Ruffalo', 'Willem Dafoe'],
    plot: 'A woman is brought back to life by a scientist.',
  },
  {
    title: 'The Favourite',
    director: 'Yorgos Lanthimos',
    genre: 'Biography',
    year: 2018,
    actors: ['Olivia Colman', 'Emma Stone', 'Rachel Weisz'],
    plot: 'Two cousins compete to be the favorite of Queen Anne.',
  },
  {
    title: 'Everything Everywhere All at Once',
    director: 'Daniel Kwan',
    genre: 'Sci-Fi',
    year: 2022,
    actors: [
      'Michelle Yeoh',
      'Stephanie Hsu',
      'Ke Huy Quan',
      'Jamie Lee Curtis',
    ],
    plot: 'A woman must save the multiverse.',
  },
  {
    title: 'Crouching Tiger, Hidden Dragon',
    director: 'Ang Lee',
    genre: 'Action',
    year: 2000,
    actors: ['Chow Yun-fat', 'Michelle Yeoh', 'Zhang Ziyi'],
    plot: 'Two warriors in pursuit of a stolen sword.',
  },
  {
    title: 'Shang-Chi and the Legend of the Ten Rings',
    director: 'Destin Daniel Cretton',
    genre: 'Action',
    year: 2021,
    actors: ['Simu Liu', 'Awkwafina', 'Tony Leung', 'Michelle Yeoh'],
    plot: 'Shang-Chi confronts his past and the Ten Rings organization.',
  },
  {
    title: 'Parasite',
    director: 'Bong Joon-ho',
    genre: 'Comedy',
    year: 2019,
    actors: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong'],
    plot: 'A poor family schemes to work for a wealthy household.',
  },
  {
    title: 'Snowpiercer',
    director: 'Bong Joon-ho',
    genre: 'Sci-Fi',
    year: 2013,
    actors: [
      'Chris Evans',
      'Song Kang-ho',
      'Tilda Swinton',
      'Octavia Spencer',
      'Jamie Bell',
      'John Hurt',
    ],
    plot: 'Survivors on a train in a frozen world.',
  },
  {
    title: 'The Host',
    director: 'Bong Joon-ho',
    genre: 'Horror',
    year: 2006,
    actors: ['Song Kang-ho', 'Byun Hee-bong', 'Park Hae-il'],
    plot: 'A monster emerges from the Han River.',
  },
  {
    title: 'Memories of Murder',
    director: 'Bong Joon-ho',
    genre: 'Crime',
    year: 2003,
    actors: ['Song Kang-ho', 'Kim Sang-kyung'],
    plot: 'Detectives hunt a serial killer in a small town.',
  },
  {
    title: 'Oldboy',
    director: 'Park Chan-wook',
    genre: 'Action',
    year: 2003,
    actors: ['Choi Min-sik', 'Yoo Ji-tae', 'Kang Hye-jung'],
    plot: 'A man seeks revenge after being imprisoned for 15 years.',
  },
  {
    title: 'The Handmaiden',
    director: 'Park Chan-wook',
    genre: 'Drama',
    year: 2016,
    actors: ['Kim Min-hee', 'Kim Tae-ri', 'Ha Jung-woo'],
    plot: 'A handmaiden is hired to defraud a Japanese heiress.',
  },
  {
    title: 'Decision to Leave',
    director: 'Park Chan-wook',
    genre: 'Mystery',
    year: 2022,
    actors: ['Park Hae-il', 'Tang Wei'],
    plot: 'A detective falls for a suspect in a murder case.',
  },
  {
    title: 'Stoker',
    director: 'Park Chan-wook',
    genre: 'Mystery',
    year: 2013,
    actors: ['Mia Wasikowska', 'Nicole Kidman', 'Matthew Goode'],
    plot: 'A girl discovers dark secrets after her father dies.',
  },
  {
    title: 'The Revenant',
    director: 'Alejandro González Iñárritu',
    genre: 'Adventure',
    year: 2015,
    actors: ['Leonardo DiCaprio', 'Tom Hardy', 'Will Poulter'],
    plot: 'Survival in the wilderness.',
  },
  {
    title: 'Peaky Blinders (The Movie)',
    director: 'Tom Harper',
    genre: 'Crime',
    year: 2024,
    actors: ['Cillian Murphy', 'Tom Hardy', 'Paul Anderson'],
    plot: 'A gangster family epic set in 1900s England.',
  },
  {
    title: 'The Last Duel',
    director: 'Ridley Scott',
    genre: 'Drama',
    year: 2021,
    actors: ['Matt Damon', 'Adam Driver', 'Jodie Comer', 'Ben Affleck'],
    plot: 'King Charles VI declares that Knight Jean de Carrouges settle his dispute with his squire by challenging him to a duel.',
  },
  {
    title: 'Air',
    director: 'Ben Affleck',
    genre: 'Drama',
    year: 2023,
    actors: ['Matt Damon', 'Ben Affleck', 'Jason Bateman', 'Viola Davis'],
    plot: 'The history of the shoe salesman who signed Michael Jordan to Nike.',
  },
  {
    title: 'Dogma',
    director: 'Kevin Smith',
    genre: 'Comedy',
    year: 1999,
    actors: ['Ben Affleck', 'Matt Damon', 'Linda Fiorentino'],
    plot: 'Two fallen angels who were cast out of heaven are now looking for a way to get back.',
  },
];
